// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6Odc8bwb6r_uupr_itEE-B7u9XwIQPk',
    appId: '1:146426615213:android:415bffa6d8199691c5bd24',
    messagingSenderId: '146426615213',
    projectId: 'seekr-hk',
    storageBucket: 'seekr-hk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbRmU5vYTixBfIuX7wznrglOTwPfVh65k',
    appId: '1:146426615213:ios:66a7f978b7d75dcfc5bd24',
    messagingSenderId: '146426615213',
    projectId: 'seekr-hk',
    storageBucket: 'seekr-hk.appspot.com',
    androidClientId: '146426615213-473ja0akthhn0c3o8oppi6v3lhmgno33.apps.googleusercontent.com',
    iosClientId: '146426615213-lg88i6152ci68dk1sia8kdh1sbnr99qm.apps.googleusercontent.com',
    iosBundleId: 'com.vidiseekr.SeekrInternal',
  );

}